In [45]:
import pandas as pd

customers_df = pd.read_csv("data/customers_raw.csv")
products_df = pd.read_csv("data/products_raw.csv")
sales_df = pd.read_csv("data/sales_raw.csv")

In [46]:
print(customers_df.shape)
print(products_df.shape)
print(sales_df.shape)

(26, 7)
(20, 5)
(41, 7)

In [47]:
customers_df.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                5
phone                0
city                 0
registration_date    0
dtype: int64

In [48]:
sales_df.duplicated().sum()

1

In [49]:
customers_df = customers_df.drop_duplicates()
print(customers_df.shape)

(25, 7)

In [50]:
sales_df = sales_df.drop_duplicates()
print(sales_df.shape)

(40, 7)

In [51]:
sales_df.duplicated().sum()

0

In [52]:
customers_df['email'] = customers_df['email'].fillna(
    customers_df['first_name'].str.lower() + "." +
    customers_df['last_name'].str.lower() + "@fleximart.com"
)

In [53]:
def clean_phone(phone):
    phone = str(phone)
    phone = phone.replace("+91", "").replace("-", "").lstrip("0")
    return "+91-" + phone[-10:]

customers_df['phone'] = customers_df['phone'].apply(clean_phone)

In [54]:
customers_df['registration_date'] = pd.to_datetime(
    customers_df['registration_date'],
    errors='coerce',
    dayfirst=True
)

C:\Users\soham\AppData\Local\Temp\ipykernel_13512\1338049698.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  customers_df['registration_date'] = pd.to_datetime(

In [55]:
customers_df['city'] = customers_df['city'].str.title()

In [56]:
customers_df.head()
customers_df.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                0
phone                0
city                 0
registration_date    5
dtype: int64

In [57]:
customers_df[customers_df['registration_date'].isna()]

,customer_id,first_name,last_name,email,phone,city,registration_date
3,C004,Sneha,Reddy,sneha.reddy@gmail.com,+91-9123456789,Hyderabad,NaT
7,C008,Pooja,Iyer,pooja.iyer@gmail.com,+91-9123456780,Bangalore,NaT
15,C015,Manish,Joshi,manish.joshi@yahoo.com,+91-9988776611,Jaipur,NaT
19,C019,Arun,Pillai,arun.pillai@outlook.com,+91-9876543298,Kochi,NaT
24,C024,Meera,Nambiar,meera.nambiar@gmail.com,+91-9123456723,Trivandrum,NaT

In [58]:
median_date = customers_df['registration_date'].median()
customers_df['registration_date'] = customers_df['registration_date'].fillna(median_date)

In [59]:
customers_df.head()
customers_df.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                0
phone                0
city                 0
registration_date    0
dtype: int64

In [60]:
products_df.isnull().sum()

product_id        0
product_name      0
category          0
price             3
stock_quantity    1
dtype: int64

In [61]:
products_df.head()

  product_id        product_name     category    price  stock_quantity
0       P001  Samsung Galaxy S21  Electronics  45999.0           150.0
1       P002  Nike Running Shoes      fashion   3499.0            80.0
2       P003   Apple MacBook Pro  ELECTRONICS      NaN            45.0
3       P004        Levi's Jeans      Fashion   2999.0           120.0
4       P005     Sony Headphones  electronics   1999.0           200.0

In [62]:
products_df['price'] = products_df.groupby('category')['price']\
.transform(lambda x: x.fillna(x.mean()))

products_df['stock_quantity'] = products_df['stock_quantity'].fillna(0)

products_df['category'] = products_df['category'].str.capitalize()

products_df['product_name'] = products_df['product_name'].str.strip()

In [63]:
products_df.isnull().sum()

product_id        0
product_name      0
category          0
price             0
stock_quantity    0
dtype: int64

In [64]:
sales_df.isnull().sum()

transaction_id      0
customer_id         3
product_id          2
quantity            0
unit_price          0
transaction_date    0
status              0
dtype: int64

In [65]:
sales_df = sales_df.drop_duplicates()

sales_df = sales_df.dropna(subset=['customer_id', 'product_id'])

In [66]:
sales_df['transaction_date'] = pd.to_datetime(
    sales_df['transaction_date'],
    errors='coerce',
    dayfirst=True
)

median_date = customers_df['registration_date'].median()
customers_df['registration_date'] = customers_df['registration_date'].fillna(median_date)

C:\Users\soham\AppData\Local\Temp\ipykernel_13512\2311675727.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  sales_df['transaction_date'] = pd.to_datetime(

In [67]:
sales_df.isnull().sum()
sales_df.head()

,transaction_id,customer_id,product_id,quantity,unit_price,transaction_date,status
0,T001,C001,P001,1,45999.0,2024-01-15,Completed
1,T002,C002,P004,2,2999.0,2024-01-16,Completed
2,T003,C003,P007,1,52999.0,NaT,Completed
4,T005,C005,P009,3,650.0,2024-01-20,Completed
5,T006,C006,P012,1,12999.0,NaT,Completed

In [68]:
print(sales_df.shape)

(35, 7)